### ISSUE TITLE
Cannot find reference to ufe82b glyph

### ISSUE THREAD

**Issue by misbatabassum** [adobe-fonts/noto-emoji-svg#73]
The font contains a glyph named ufe82b, and we don't know where this comes from. U+FE82B is a codepoint in a Private Use Area. Checked the previous version (1.001) and the ufe82b glyph is there too.

**Comment by miguelsousa** [comment]
Mystery solved.
A file named **ufe82b.svg** (née [emoji_ufe82b.svg](https://github.com/adobe-fonts/noto-emoji-svg/commits/master/svg_bw/emoji_ufe82b.svg)) exists at https://github.com/adobe-fonts/noto-emoji-svg/blob/master/svg_bw/ufe82b.svg. The artwork is a blank flag with a question mark ([see PNG](https://github.com/adobe-fonts/noto-emoji-svg/blob/master/png/ufe82b.png)).

The file has been part of this repository since the very first commit, which means it was inherited from the [Noto Emoji](https://github.com/googlefonts/noto-emoji) repo. Doing a search there, and inspecting their font, reveals that the [PUA-encoded "unknown flag" emoji](https://github.com/googlefonts/noto-emoji/blob/c05b4b47c8250ccd232780cae46d66a8179e77ab/check_emoji_sequences.py#L104) is used for representing combination pairs of REGIONAL INDICATOR SYMBOL LETTER characters which don't have a country assigned (e.g. U+1F1E6, U+1F1E6 — 🇦🇦 — AA).
